/// A short line for each letter: (Kannada, romanised, English). Written with
/// Gemini at build time (tool/gemini_content.py), checked by a Kannada
/// speaker, spoken by Sarvam's Kavya voice. Generated by
/// tool/import_lines.py; the app never calls an AI service.
const letterLines = <String, (String, String, String)>{};
