/// A short line for each letter: (Kannada, romanised, English). Written with
/// Gemini at build time (tool/gemini_content.py), checked by a Kannada
/// speaker, spoken by Sarvam's Kavya voice. Generated by
/// tool/import_lines.py; the app never calls an AI service.
const letterLines = <String, (String, String, String)>{
  'ಅ': (
    'ಅನಾನಸ್ ಹಣ್ಣು ತುಂಬಾ ಸಿಹಿಯಾಗಿದೆ.',
    'anaanas haNNu thumba sihiyaagide.',
    'Pineapple fruit is very sweet.',
  ),
  'ಆ': (
    'ಆನೆ ಅಂಬಾರಿ ಹೊತ್ತು ನಡೆಯುತ್ತಿದೆ.',
    'aane ambaari hotthu nadeyuthide.',
    'The elephant is walking carrying a howdah.',
  ),
  'ಇ': (
    'ಇಲಿ ಚಿಕ್ಕದಾಗಿ ಓಡಿಹೋಗುತ್ತಿದೆ.',
    'ili chikkadaagi oodihoguthide.',
    'The mouse is running away small.',
  ),
  'ಈ': (
    'ಈರುಳ್ಳಿ ಅಡುಗೆಗೆ ತುಂಬಾ ರುಚಿ ನೀಡುತ್ತದೆ.',
    'iiruLLi adugege thumba ruchi needuthade.',
    'Onion gives a lot of taste to cooking.',
  ),
  'ಉ': (
    'ಉಂಗುರ ನನ್ನ ಕೈಗೆ ಚೆನ್ನಾಗಿದೆ.',
    'ungura nanna kaige chennagide.',
    'The ring looks nice on my hand.',
  ),
  'ಊ': (
    'ಊಟ ಮಾಡಿ ಚೆನ್ನಾಗಿ ಆಟವಾಡಿ.',
    'uuTa maaDi chennaagi aaTavaaDi.',
    'Eat your meal and play well.',
  ),
  'ಋ': (
    'ಋಷಿ ಆಶ್ರಮದಲ್ಲಿ ಶಾಂತಿಯಿಂದ ಕುಳಿತಿದ್ದಾರೆ.',
    'rushi aashramadalli shaanthiyinda kuLithiddare.',
    'The sage is sitting peacefully in the ashram.',
  ),
  'ಎ': (
    'ಎಲೆ ಹಸಿರು ಬಣ್ಣದಲ್ಲಿ ಸುಂದರವಾಗಿದೆ.',
    'ele hasiru baNNadalli sundaravaagide.',
    'The leaf is beautiful in green color.',
  ),
  'ಏ': (
    'ಏಣಿ ಹತ್ತಿ ಮೇಲೆ ಹೋಗೋಣ ಬನ್ನಿ.',
    'eeNi hatthi mele hoogooNa banni.',
    'Come, let us climb the ladder and go up.',
  ),
  'ಐ': (
    'ನನ್ನ ಕೈಯಲ್ಲಿ ಐದು ಬೆರಳುಗಳಿವೆ.',
    'nanna kaiyalli aidu beraLugalive.',
    'I have five fingers on my hand.',
  ),
  'ಒ': (
    'ಒಂಟೆ ಮರುಭೂಮಿಯಲ್ಲಿ ವೇಗವಾಗಿ ನಡೆಯುತ್ತದೆ.',
    'onTe marubhoomiyalli vegavaagi nadeyuthade.',
    'The camel walks fast in the desert.',
  ),
  'ಓ': (
    'ಪುಸ್ತಕ ಓದು ಅಭ್ಯಾಸ ಮಾಡಿಕೊಳ್ಳಿ.',
    'pustaka oodu abhyaasa maaDikolli.',
    'Make a habit of reading books.',
  ),
  'ಔ': (
    'ಔಷಧಿ ಸೇವಿಸಿದರೆ ಆರೋಗ್ಯ ಸುಧಾರಿಸುತ್ತದೆ.',
    'aushadhi sevisidare aarogya sudhaarissuthade.',
    'Health improves if medicine is taken.',
  ),
  'ಅಂ': (
    'ಅಂಗಡಿ ಮುಂದೆ ಬಣ್ಣದ ಆಟಿಕೆಗಳಿವೆ.',
    'angaDi munde baNNada aaTakegalive.',
    'There are colorful toys in front of the shop.',
  ),
  'ಕ': (
    'ಕಮಲ ಹೂವು ನೀರಿನಲ್ಲಿ ಅರಳಿದೆ.',
    'kamala hoovu neerinalli araLide.',
    'The lotus flower has blossomed in the water.',
  ),
  'ಖ': (
    'ರಾಜನು ಖಡ್ಗ ಹಿಡಿದು ನಿಂತಿದ್ದಾನೆ.',
    'raajanu khaDga hiDidu ninthiddane.',
    'The king is standing holding a sword.',
  ),
  'ಗ': (
    'ಗಡಿಯಾರ ಟಿಕ್ ಟಿಕ್ ಎಂದು ಸದ್ದು ಮಾಡುತ್ತದೆ.',
    'gaDiyaara Tik Tik endu saddu maaDuthade.',
    'The clock makes a tick-tick sound.',
  ),
  'ಘ': (
    'ಘಂಟೆ ಸದ್ದು ಕೇಳಿ ದೇವಸ್ಥಾನಕ್ಕೆ ಹೋಗೋಣ.',
    'ghanTe saddu keLi devasthaanakke hoogooNa.',
    'Let us go to the temple hearing the bell sound.',
  ),
  'ಚ': (
    'ಚಮಚ ಬಳಸಿ ಹಾಲು ಕುಡಿಯಿರಿ.',
    'chamacha baLasi haalu kuDiyiri.',
    'Drink milk using a spoon.',
  ),
  'ಜ': (
    'ಜಿಂಕೆ ಕಾಡಿನಲ್ಲಿ ವೇಗವಾಗಿ ಓಡುತ್ತದೆ.',
    'jinke kaaDinalli vegavaagi ooDuthade.',
    'The deer runs fast in the forest.',
  ),
  'ಝ': (
    'ಝರಿ ನೀರು ಹರಿಯುವ ಸದ್ದು ಸುಂದರ.',
    'jhari neeru hariyuva saddu sundara.',
    'The sound of the flowing stream is beautiful.',
  ),
  'ಟ': (
    'ಟಗರು ಜೋರಾಗಿ ಓಡಿ ಬರುತ್ತದೆ ನೋಡಿ!',
    'Tagaru jooraagi ooDi baruttade nooDi!',
    'Look, the ram comes running fast!',
  ),
  'ಡ': (
    'ಶಿವನ ಕೈಯಲ್ಲಿ ಡಮರು ಸದ್ದು ಮಾಡುತ್ತದೆ!',
    'Shivana kaiyalli Damaru saddu maaDuttade!',
    'The hand drum in Shiva\'s hand makes a sound!',
  ),
  'ಢ': (
    'ಢಕ್ಕೆ ಬಾರಿಸಿದಾಗ ಡಂ ಡಂ ಶಬ್ದ ಕೇಳಿಸುತ್ತದೆ.',
    'Dhakke baarisidaaga Dam Dam shabda keeLisuttade.',
    'When the drum is played, a Dam Dam sound is heard.',
  ),
  'ದ': (
    'ದನ ಹುಲ್ಲು ತಿಂದು ಸಿಹಿ ಹಾಲು ನೀಡುತ್ತದೆ.',
    'Dana hullu tindu sihi haalu niiDuttade.',
    'The cow eats grass and gives sweet milk.',
  ),
  'ಧ': (
    'ನಮ್ಮ ದೇಶದ ಧ್ವಜ ಗಗನದಲ್ಲಿ ಹಾರಾಡುತ್ತದೆ!',
    'Namma deeshada dhvaja gaganadalli haaraaDuttade!',
    'Our country\'s flag flies high in the sky!',
  ),
  'ನ': (
    'ನವಿಲು ಗರಿ ಬಿಚ್ಚಿ ಚಂದವಾಗಿ ಕುಣಿಯುತ್ತದೆ!',
    'Navilu gari bicchi chandavaagi kuNiyuttade!',
    'The peacock spreads its feathers and dances beautifully!',
  ),
  'ಪ': (
    'ನನ್ನ ಬಳಿ ಬಣ್ಣದ ಚಿತ್ರಗಳ ಪುಸ್ತಕವಿದೆ.',
    'Nanna baLi baNNada chitragala pustakavide.',
    'I have a book of colorful pictures.',
  ),
  'ಫ': (
    'ದಿನವೂ ಸಿಹಿಯಾದ ಫಲ ತಿನ್ನುವುದು ತುಂಬಾ ಒಳ್ಳೆಯದು.',
    'Dinavuu sihiyaada phala tinnuvudu tumbaa olleyadu.',
    'Eating sweet fruit every day is very good.',
  ),
  'ಭ': (
    'ನಮ್ಮ ಸುಂದರ ಭೂಮಿ ಹಸಿರಿನಿಂದ ಕಂಗೊಳಿಸುತ್ತದೆ.',
    'Namma sundara bhuumi hasirininda kaNgoLisuttade.',
    'Our beautiful Earth shines with greenery.',
  ),
  'ಮ': (
    'ದೊಡ್ಡ ಮರ ನಮಗೆ ತಂಪಾದ ನೆರಳು ಕೊಡುತ್ತದೆ.',
    'DoDDa mara namage tampaada neraLu koDuttade.',
    'The big tree gives us cool shade.',
  ),
  'ರ': (
    'ರೈಲು ಕೂಗುತ್ತಾ ಕಂಬಿಯ ಮೇಲೆ ಓಡುತ್ತದೆ!',
    'Railu kuuguthaa kambiya meele ooDuttade!',
    'The train whistles and runs on the track!',
  ),
  'ಲ': (
    'ದೊಡ್ಡ ಲಾರಿ ರಸ್ತೆಯಲ್ಲಿ ವೇಗವಾಗಿ ಹೋಗುತ್ತದೆ.',
    'DoDDa laari rasteyalli veegavaagi hooguttade.',
    'The big lorry goes fast on the road.',
  ),
  'ಸ': (
    'ಬೆಳಿಗ್ಗೆ ಸೂರ್ಯ ಮೂಡಿ ನಮಗೆ ಬೆಳಕು ನೀಡುತ್ತಾನೆ.',
    'BeLigge suurya muuDi namage beLaku niiDuttaane.',
    'The sun rises in the morning and gives us light.',
  ),
  'ಅಃ': (
    'ಮಕ್ಕಳು ದುಃಖ ಪಡದೆ ನಗುತ್ತಿರಬೇಕು.',
    'makkaLu duhkha paDade nagutthirabeku.',
    'Children should stay smiling without sadness.',
  ),
  'ಙ': (
    'ವಾಙ್ಮಯ ಓದುವುದು ಜ್ಞಾನಕ್ಕೆ ಒಳ್ಳೆಯದು.',
    'vaangmaya ooduvudu jnaanakke oLLeyadu.',
    'Reading literature is good for knowledge.',
  ),
  'ಛ': (
    'ಮಳೆ ಬಂದರೆ ಛತ್ರಿ ಹಿಡಿದು ನಡೆಯಿರಿ.',
    'maLe bandare chhatri hiDidu naDeyiri.',
    'Walk holding an umbrella if it rains.',
  ),
  'ಞ': (
    'ಜ್ಞಾನ ಗಳಿಸಲು ಪುಸ್ತಕ ಓದಬೇಕು.',
    'jnaana gaLisalu pustaka oodabeku.',
    'One must read books to gain knowledge.',
  ),
  'ಠ': (
    'ಆ ಚಿಕ್ಕ ಮಠ ತುಂಬಾ ಸುಂದರವಾಗಿದೆ.',
    'Aa chikka maTha tumbaa sundaravaagide.',
    'That small monastery is very beautiful.',
  ),
  'ಣ': (
    'ರಾಜನು ದೂರಕ್ಕೆ ಬಾಣ ಬಿಟ್ಟನು ನೋಡಿ!',
    'Raajanu doorakke baaNa biTTanu nooDi!',
    'Look, the king shot an arrow far away!',
  ),
  'ತ': (
    'ಅಮ್ಮ ತಂದ ತರಕಾರಿ ಆರೋಗ್ಯಕ್ಕೆ ತುಂಬಾ ಒಳ್ಳೆಯದು.',
    'Amma tanda tarakaari aarogyakke tumbaa olleyadu.',
    'Vegetables brought by mother are very good for health.',
  ),
  'ಥ': (
    'ಅಜ್ಜಿ ನಮಗೆ ಚಂದದ ಕಥೆ ಹೇಳುತ್ತಾರೆ.',
    'Ajji namage chandada kathe heeLuttaare.',
    'Grandmother tells us a lovely story.',
  ),
  'ಬ': (
    'ಬಾತುಕೋಳಿ ನೀರಿನಲ್ಲಿ ಈಜುತ್ತಾ ಖುಷಿಯಿಂದ ಹೋಗುತ್ತದೆ.',
    'BaatukoLi niirinalli iijuthaa khuShiyinda hooguttade.',
    'The duck swims happily in the water.',
  ),
  'ಯ': (
    'ಈ ಹೊಸ ಯಂತ್ರ ಬೇಗ ಕೆಲಸ ಮಾಡುತ್ತದೆ.',
    'Ee hosa yantra beega kelasa maaDuttade.',
    'This new machine works fast.',
  ),
  'ವ': (
    'ಹೊಳೆಯುವ ವಜ್ರ ನೋಡಲು ತುಂಬಾ ಚೆನ್ನಾಗಿದೆ.',
    'HoLeyuva vajra nooDalu tumbaa chennaagide.',
    'The glowing diamond looks very nice.',
  ),
  'ಶ': (
    'ದೇವಸ್ಥಾನದಲ್ಲಿ ಶಂಖ ಊದಿದಾಗ ಮಧುರ ಶಬ್ದ ಬರುತ್ತದೆ.',
    'Deevasthaanadalli shankha uudidaaga madhura shabda baruttade.',
    'When the conch is blown at the temple, a sweet sound comes.',
  ),
  'ಷ': (
    'ರೈತರು ಹೊಲದಲ್ಲಿ ಪ್ರೀತಿಯಿಂದ ಕೃಷಿ ಮಾಡುತ್ತಾರೆ.',
    'Raitaru holadalli priitiyinda krushi maaDuttaare.',
    'Farmers do farming lovingly in the field.',
  ),
  'ಹ': (
    'ತೋಟದಲ್ಲಿ ಕೆಂಪು ಹೂವು ಚಂದವಾಗಿ ಅರಳಿದೆ!',
    'TooTadalli kempu huuvu chandavaagi araLide!',
    'The red flower has bloomed beautifully in the garden!',
  ),
  'ಳ': (
    'ಮಗು ಆಸೆಯಿಂದ ಸಿಹಿಯಾದ ಬಾಳೆಹಣ್ಣು ತಿಂದಿತು.',
    'Magu aaseyinda sihiyaada baaLehaNNu tinditu.',
    'The child ate the sweet banana with delight.',
  ),
};
